# Generated by Django 4.2.1 on 2023-05-30 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(help_text='Enter brand', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='carcass',
            field=models.ForeignKey(help_text='Choose carcass type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.carcasstype'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(help_text='Enter color', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(help_text='Enter description'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(help_text='Enter model', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='producer',
            field=models.ForeignKey(help_text='Choose producer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.producer'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year_of_publication',
            field=models.IntegerField(help_text='Enter year of publication'),
        ),
        migrations.AlterField(
            model_name='carcasstype',
            name='designation',
            field=models.CharField(help_text='Enter type', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(help_text='Enter date of birth'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(help_text='Enter email', max_length=254),
        ),
        migrations.AlterField(
            model_name='producer',
            name='country',
            field=models.CharField(help_text='Enter country', max_length=20),
        ),
        migrations.AlterField(
            model_name='producer',
            name='owner',
            field=models.CharField(help_text='Enter owner', max_length=20),
        ),
    ]
