# Generated by Django 4.2.1 on 2023-05-31 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_car_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='carcass',
            new_name='carcass_type',
        ),
    ]
