# Generated by Django 4.1.9 on 2023-09-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_car_purchase_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter title', max_length=50)),
                ('essence', models.CharField(help_text='Enter essence', max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='images')),
                ('description', models.TextField(help_text='Enter description')),
            ],
        ),
    ]
