# Generated by Django 4.1.9 on 2023-09-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Enter question', max_length=50)),
                ('answer', models.TextField(help_text='Enter answer')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
