# Generated by Django 4.1.9 on 2023-09-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_faq_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_job', models.CharField(help_text='Enter type of ypor job', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter first name', max_length=20)),
                ('last_name', models.CharField(help_text='Enter last name', max_length=20)),
                ('email', models.EmailField(help_text='Enter email', max_length=254)),
                ('phone_number', models.CharField(help_text='Enter phone number', max_length=15)),
                ('photo', models.ImageField(blank=True, upload_to='images')),
                ('job', models.ManyToManyField(help_text='Choose type(s) of job', to='main.job')),
            ],
        ),
    ]
