# Generated by Django 4.1.9 on 2023-09-13 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_job_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(help_text='Enter phone number', max_length=25, validators=[django.core.validators.RegexValidator(message='Format +375 (29) XXX-XX-XX', regex='^(\\+375 \\(29\\) [0-9]{3}-[0-9]{2}-[0-9]{2})$')]),
        ),
    ]
