# Generated by Django 4.1.9 on 2023-09-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_employee_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type_of_job',
            field=models.CharField(help_text='Enter type of ypor job', max_length=70),
        ),
    ]
