# Generated by Django 4.1.9 on 2023-09-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_job_type_of_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='', help_text='Enter description'),
        ),
    ]
