# Generated by Django 4.1.9 on 2023-09-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_actual',
            field=models.BooleanField(default=False, help_text='Is actual?'),
        ),
    ]
