# Generated by Django 4.1.9 on 2023-09-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_promotional_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotional_code',
            name='is_actual',
            field=models.BooleanField(default=False),
        ),
    ]
