# Generated by Django 4.1.9 on 2023-09-15 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_promotional_code_is_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotional_code',
            name='discount',
            field=models.IntegerField(default=10, help_text='Enter discount from 1 to 25', validators=[django.core.validators.MinValueValidator(1, message='The number cannot be less than 1'), django.core.validators.MaxValueValidator(25, message='The number cannot be more than 25')]),
        ),
    ]
