# Generated by Django 4.1.9 on 2023-09-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_promotional_code_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='town',
            field=models.CharField(default='Minsk', help_text='Enter town', max_length=30),
        ),
    ]
