# Generated by Django 4.1.9 on 2023-10-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_client_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='essence',
            field=models.CharField(help_text='Enter essence', max_length=350),
        ),
    ]
