# Generated by Django 4.1.9 on 2023-09-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sale_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
